# Application
spring.application.name=commerce-service
spring.profiles.active=local
spring.messages.encoding=UTF-8

# HikariCP
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.connection-timeout=10000

# JPA/Hibernate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100

# DB Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
jwt.expiration-period=1800000

# File Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Kakao Map API
kakao.rest-api-key=${KAKAO_REST_API_KEY}