# \uACF5\uD1B5 \uC124\uC815 (Local, AWS)
spring.application.name=commerce-service
server.servlet.session.tracking-modes=cookie
server.servlet.session.timeout=1800
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP \uC124\uC815
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.connection-timeout=10000

# JPA/Hibernate \uACF5\uD1B5 \uC124\uC815
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.messages.encoding=UTF-8

# local \uD504\uB85C\uD30C\uC77C \uD65C\uC131\uD654
spring.profiles.active=local